---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie-test
  namespace: mealie-test
spec:
  interval: 15m
  chart:
    spec:
      chart: mealie
      version: 26.3.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3:
        type: s3
        url: "${S3URL}"
        bucket: "${S3PREFIX}-rand1"
        accessKey: "${S3ID}"
        secretKey: "${S3KEY}"
        encrKey: "${S3KEY}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: mealie-test.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      data:
        volsync:
          - name: data
            type: restic
            credentials: s3
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: "30 21 * * *"
    cnpg:
      main:
        mode: recovery
        cluster:
          singleNode: true
        backups:
          enabled: true
          retentionPolicy: "7d"
          credentials: s3
          scheduledBackups:
            - name: daily-backup
              schedule: "30 21 * * *"
              backupOwnerReference: self
              immediate: true
              suspend: false
        recovery:
          method: object_store
          credentials: s3
