---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/refs/heads/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 15m
  chart:
    spec:
      chart: homepage
      version: 11.4.6
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
      reconcileStrategy: Revision
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                HOMEPAGE_ALLOWED_HOSTS: home.${DOMAIN_0}
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        hosts:
          - host: home.${DOMAIN_0}
    persistence:
      public:
        enabled: true
        mountPath: /app/public/images
