apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm-repos
  namespace: flux-system
resources:
  - bjw-s.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - csi-driver-nfs.yaml
  - descheduler.yaml
  - jetstack.yaml
  - kustomization.yaml
  - longhorn.yaml
  - metallb.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - nvidia.yaml
  - openebs.yaml
  - prometheus-community.yaml
  - stakater.yaml
  - truecharts.yaml
  - weave-gitops.yaml
  - grafana.yaml
  - traefik.yaml
  - home-ops-mirror.yaml
# more goes here!