---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Pull Request: Validate"

on:
  pull_request:
    branches: ["main"]
    paths: ["clusters/main/kubernetes/**"]
concurrency:
  group: ${{ github.head_ref }}-pr-validate
  cancel-in-progress: true
env:
  KUBERNETES_DIR: ./clusters/main/kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Setup Workflow Tools
        run: brew install fluxcd/tap/flux kubeconform kustomize
      - name: Run kubeconform
        shell: bash
        run: bash ./scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
  flux-test:
    name: Flux Local - Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Substitute placeholder
        uses: faradaytrs/substitute-secrets-action@26e9dfb248ba425dcb806a0f54e274ef7e8448f7 # 2.4
        with:
          input: 'clusters/main/kubernetes/**/*.yaml'
          substitutionRegex: '\$\{(\w+)\}'
          substitutionData: '{"S3URL":"https://placeholder.example"}'
          throwOnDataMissing: false
      - name: Run flux-local test
        uses: docker://ghcr.io/allenporter/flux-local:v7.8.0@sha256:e8cd431e824eddd169763e02ef73ebb76c40740f1e1e67f6234a29b28304ce9c
        with:
          args: >-
            test
            --all-namespaces
            --api-versions=monitoring.coreos.com/v1
            --enable-helm
      - name: Undo any changes (if needed)
        run: |
          git checkout -- clusters/main/kubernetes/
  flux-diff:
    name: Flux Diff
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          path: pull
      - name: Substitute placeholder
        uses: faradaytrs/substitute-secrets-action@26e9dfb248ba425dcb806a0f54e274ef7e8448f7 # 2.4
        with:
          input: 'pull/clusters/main/kubernetes/**/*.yaml'
          substitutionRegex: '\$\{(\w+)\}'
          substitutionData: '{"S3URL":"https://placeholder.example"}'
          throwOnDataMissing: false
      - name: Checkout Default Branch
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: "${{ github.event.repository.default_branch }}"
          path: default
      - name: Substitute placeholder
        uses: faradaytrs/substitute-secrets-action@26e9dfb248ba425dcb806a0f54e274ef7e8448f7 # 2.4
        with:
          input: 'default/clusters/main/kubernetes/**/*.yaml'
          substitutionRegex: '\$\{(\w+)\}'
          substitutionData: '{"S3URL":"https://placeholder.example"}'
          throwOnDataMissing: false
      - name: Diff HelmReleases
        uses: ./pull/.github/actions/helm-diff
        with:
          retries: 3
      - name: Diff Kustomizations
        uses: docker://ghcr.io/allenporter/flux-local:v7.8.0@sha256:e8cd431e824eddd169763e02ef73ebb76c40740f1e1e67f6234a29b28304ce9c
        with:
          args: >
            diff kustomization
            --unified 6
            --path /github/workspace/pull/
            --path-orig /github/workspace/default/
            --strip-attrs "helm.sh/chart,checksum/config,checksum/redis,checksum/secrets,app.kubernetes.io/version,chart,app"
            --limit-bytes 10000
            --all-namespaces
            --sources "cluster"
            --output-file diff-kustomization.patch
      - name: Generate Merged Diff
        id: diff
        run: |
          {
            echo "diff<<EOF" >> $GITHUB_OUTPUT
      
            echo "### HelmRelease Diff" >> $GITHUB_OUTPUT
            echo '```diff' >> $GITHUB_OUTPUT
            cat diff-helmrelease.patch >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
      
            echo "" >> $GITHUB_OUTPUT
      
            echo "### Kustomization Diff" >> $GITHUB_OUTPUT
            echo '```diff' >> $GITHUB_OUTPUT
            cat diff-kustomization.patch >> $GITHUB_OUTPUT
            echo '```' >> $GITHUB_OUTPUT
      
            echo "EOF" >> $GITHUB_OUTPUT
          }
      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - if: ${{ steps.diff.outputs.diff != '' }}
        name: Add Comment
        uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
        with:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          header: ${{ github.event.pull_request.number }}/kubernetes/diff
          message: ${{ steps.diff.outputs.diff }}

  automerge-and-approve:
    needs:
      - kubeconform
      - flux-diff
      - flux-test
    permissions:
      pull-requests: write
      contents: write
    name: Automerge and Approve build
    runs-on: ubuntu-latest
    steps:
      - name: Generate Token
        uses: actions/create-github-app-token@a8d616148505b5069dccd32f177bb87d7f39123b # v2.1.1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}
      - name: automerge
        uses: pascalgn/automerge-action@7961b8b5eec56cc088c140b56d864285eabd3f67 # v0.16.4
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          UPDATE_RETRIES: 12
          UPDATE_RETRY_SLEEP: 60000
          MERGE_METHOD: squash
